# Intro Machine Learning - Tuần 9

Notebook này tóm tắt 3 nội dung chính:

1. Machine Learning là gì? Supervised vs Unsupervised
2. Pipeline Machine Learning: dữ liệu → xử lý → model → đánh giá
3. Các dạng bài toán: Classification, Regression, Clustering

---

# 1. Machine Learning là gì?

**Machine Learning (ML)** là một nhánh của AI, nơi máy tính học quy luật từ dữ liệu để dự đoán hoặc ra quyết định.

Thay vì con người viết từng rule bằng tay, ta đưa dữ liệu cho model và model tự học pattern.

Ví dụ truyền thống:

```text
Nếu email chứa từ "free", "win", "money" → spam
```

Ví dụ Machine Learning:

```text
Đưa nhiều email đã có nhãn spam/not spam
→ model tự học đặc điểm của email spam
→ dự đoán email mới
```

## Cốt lõi của ML

ML thường đi theo logic:

```text
Input X → Model học pattern → Output Y
```

Ví dụ:

| Input X | Output Y |
|---|---|
| Diện tích nhà | Giá nhà |
| Nội dung email | Spam / Not spam |
| Ảnh | Mèo / Chó |
| Tuổi, thu nhập khách hàng | Có mua hàng hay không |

## “Học” trong ML nghĩa là gì?

Trong ML, **học** nghĩa là model tự điều chỉnh tham số để giảm sai số.

Ví dụ model dự đoán giá nhà:

```text
Prediction = 5 tỷ
Actual = 7 tỷ
Sai số = 2 tỷ
```

Model sẽ điều chỉnh tham số để lần sau dự đoán gần đúng hơn.

Đây là lý do các kiến thức trước rất quan trọng:

- Loss Function: đo model sai bao nhiêu
- Gradient Descent / SGD / Adam: cách model tự chỉnh tham số
- Gradient / đạo hàm: cho biết nên chỉnh theo hướng nào

---

# 2. Supervised Learning là gì?

**Supervised Learning** là học có đáp án sẵn.

Ta đưa cho model cả:

```text
Input X + Label Y
```

Ví dụ:

| Area | Rooms | Price |
|---|---:|---:|
| 50m² | 2 | 5 tỷ |
| 70m² | 3 | 7 tỷ |
| 100m² | 4 | 10 tỷ |

Ở đây:

- X = Area, Rooms
- Y = Price

Model học từ dữ liệu đã có đáp án để dự đoán cho dữ liệu mới.

## Vì sao gọi là Supervised?

Vì model được “giám sát” bằng label đúng.

Ví dụ:

```text
Đây là email spam
Đây là email không spam
Đây là ảnh mèo
Đây là ảnh chó
```

Model học từ những đáp án đó.

## Supervised Learning gồm 2 dạng chính

### 1. Regression

Dự đoán **giá trị số liên tục**.

Ví dụ:

- Dự đoán giá nhà
- Dự đoán doanh thu
- Dự đoán nhiệt độ
- Dự đoán lương

Output dạng:

```text
5.2 tỷ, 120 triệu, 32.5 độ
```

### 2. Classification

Dự đoán **nhãn / loại**.

Ví dụ:

- Spam / Not spam
- Bệnh / Không bệnh
- Mèo / Chó
- Khách mua / Không mua

Output dạng:

```text
0/1, Yes/No, Cat/Dog
```

---

# 3. Unsupervised Learning là gì?

**Unsupervised Learning** là học không có đáp án sẵn.

Ta chỉ đưa cho model dữ liệu X, không có label Y.

```text
Input X → Model tự tìm pattern
```

Ví dụ dữ liệu khách hàng:

| Age | Income |
|---:|---:|
| 20 | 500 |
| 22 | 600 |
| 45 | 5000 |
| 50 | 6000 |

Model có thể tự nhận ra:

- Nhóm khách trẻ, thu nhập thấp
- Nhóm khách lớn tuổi hơn, thu nhập cao

Không ai nói trước nhóm nào là nhóm nào. Model tự phân cụm dựa trên sự giống nhau của dữ liệu.

## So sánh Supervised vs Unsupervised

| Tiêu chí | Supervised Learning | Unsupervised Learning |
|---|---|---|
| Có label không? | Có | Không |
| Mục tiêu | Dự đoán output | Tìm pattern / nhóm |
| Dữ liệu | X và Y | Chỉ có X |
| Bài toán thường gặp | Classification, Regression | Clustering |
| Ví dụ | Dự đoán giá nhà, spam email | Phân nhóm khách hàng |

In [1]:
# Ví dụ nhỏ: dữ liệu supervised có X và y

import pandas as pd

data_supervised = pd.DataFrame({
    "Age": [22, 25, 35, 45],
    "Salary": [500, 700, 2000, 4000],
    "Buy": [0, 0, 1, 1]  # label / target
})

data_supervised

   Age  Salary  Buy
0   22     500    0
1   25     700    0
2   35    2000    1
3   45    4000    1

In [2]:
# Ví dụ nhỏ: dữ liệu unsupervised chỉ có X, không có y

data_unsupervised = pd.DataFrame({
    "Age": [22, 25, 35, 45],
    "Salary": [500, 700, 2000, 4000]
})

data_unsupervised

   Age  Salary
0   22     500
1   25     700
2   35    2000
3   45    4000

---

# 4. Machine Learning Pipeline

Pipeline là quy trình chuẩn để xây dựng một bài toán ML.

Pipeline cơ bản:

```text
Dữ liệu → xử lý dữ liệu → model → đánh giá
```

Phiên bản đầy đủ hơn:

```text
Thu thập dữ liệu
→ Làm sạch dữ liệu
→ Feature engineering
→ Chia train/test
→ Train model
→ Predict
→ Evaluation
→ Cải thiện model
```

## Bước 1: Dữ liệu

Dữ liệu là nền móng của ML.

Nếu dữ liệu xấu, model sẽ học sai.

Câu dễ nhớ:

```text
Garbage in → Garbage out
```

Ví dụ dữ liệu có vấn đề:

| Age | Salary | Buy |
|---:|---:|---|
| 22 | 500 | Yes |
| 25 | NaN | No |
| 300 | 1000 | Yes |

Vấn đề:

- Salary bị thiếu
- Age = 300 là vô lý
- Buy là text, model thường cần chuyển thành số

## Bước 2: Xử lý dữ liệu

Xử lý dữ liệu còn gọi là **Data Preprocessing**.

Các việc thường làm:

### 1. Missing Values

Dữ liệu bị thiếu, ví dụ `NaN`.

Cách xử lý:

- Xóa dòng bị thiếu
- Thay bằng mean
- Thay bằng median

### 2. Encoding

Model không hiểu text trực tiếp.

Ví dụ:

```text
Male/Female → 0/1
Yes/No → 1/0
```

### 3. Feature Scaling

Đưa các biến về thang đo hợp lý.

Ví dụ `Salary` có giá trị rất lớn so với `Age`, nên có thể làm model bị lệch.

### 4. Feature Engineering

Tạo feature mới từ dữ liệu cũ.

Ví dụ:

```text
Year_Birth → Age
Weight + Height → BMI
Order_Date → Month, Day, Weekday
```

Trong thực tế, feature tốt đôi khi quan trọng hơn model mạnh.

## Bước 3: Chia Train/Test

Không nên train và đánh giá trên cùng một dữ liệu.

Ví dụ có 1000 dòng dữ liệu:

```text
800 dòng → train
200 dòng → test
```

Mục tiêu:

- Train set: để model học
- Test set: để kiểm tra model có dự đoán tốt trên dữ liệu mới không

Nếu model chỉ giỏi trên train nhưng tệ trên test, đó thường là **overfitting**.

## Bước 4: Train Model

Đây là lúc model học từ dữ liệu.

Quá trình học thường có logic:

```text
Prediction
→ Tính loss
→ Dùng optimizer để giảm loss
→ Update weights
→ Prediction tốt hơn
```

Các model phổ biến:

- Linear Regression
- Logistic Regression
- Decision Tree
- Random Forest
- K-Means
- Neural Network

## Bước 5: Đánh giá model

Sau khi train, cần đo model tốt hay tệ.

Với **Regression**, hay dùng:

- MAE
- MSE
- RMSE

Với **Classification**, hay dùng:

- Accuracy
- Precision
- Recall
- F1-score

Mục tiêu cuối cùng của ML không phải học thuộc dữ liệu train, mà là dự đoán tốt trên dữ liệu mới. Đây gọi là **Generalization**.

In [3]:
# Demo nhỏ: quy trình chia X và y

df = pd.DataFrame({
    "Age": [22, 25, 30, 35, 40, 45],
    "Salary": [500, 700, 1200, 2000, 3000, 4000],
    "Buy": [0, 0, 0, 1, 1, 1]
})

X = df[["Age", "Salary"]]  # input features
y = df["Buy"]              # target / label

print("X:")
display(X)

print("y:")
display(y)

X:

   Age  Salary
0   22     500
1   25     700
2   30    1200
3   35    2000
4   40    3000
5   45    4000

y:

0    0
1    0
2    0
3    1
4    1
5    1
Name: Buy, dtype: int64

---

# 5. Các dạng bài toán trong ML

Có 3 dạng cơ bản cần nắm:

1. Classification
2. Regression
3. Clustering

Cách nhận diện nhanh nhất:

```text
Output là nhãn → Classification
Output là số → Regression
Không có label, muốn chia nhóm → Clustering
```

## 5.1 Classification

**Classification** là bài toán dự đoán nhãn hoặc loại.

Output là category, không phải số liên tục.

Ví dụ:

| Bài toán | Output |
|---|---|
| Email spam | Spam / Not spam |
| Chẩn đoán bệnh | Bệnh / Không bệnh |
| Nhận diện ảnh | Cat / Dog |
| Dự đoán khách mua hàng | Buy / Not buy |

Classification có thể là:

- Binary classification: 2 lớp, ví dụ 0/1, Yes/No
- Multi-class classification: nhiều lớp, ví dụ Cat/Dog/Bird

## 5.2 Regression

**Regression** là bài toán dự đoán giá trị số.

Output là số liên tục.

Ví dụ:

| Bài toán | Output |
|---|---|
| Dự đoán giá nhà | 8.5 tỷ |
| Dự đoán doanh thu | 120 triệu |
| Dự đoán nhiệt độ | 32.5 độ |
| Dự đoán lương | 2000 SGD |

Điểm chính:

```text
Regression trả ra con số
Classification trả ra nhãn
```

## 5.3 Clustering

**Clustering** là bài toán tự chia nhóm dữ liệu giống nhau.

Đây là dạng Unsupervised Learning vì không có label ban đầu.

Ví dụ:

| Bài toán | Mục tiêu |
|---|---|
| Phân nhóm khách hàng | Nhóm VIP, nhóm phổ thông, nhóm nhạy giá |
| Phân nhóm sản phẩm | Nhóm sản phẩm giống nhau |
| Phân nhóm hành vi user | User hay mua, user hay xem, user ít hoạt động |

Model không biết trước tên nhóm. Nó chỉ phát hiện các điểm dữ liệu giống nhau và gom lại.

## So sánh Classification, Regression, Clustering

| Dạng bài toán | Output | Có label? | Thuộc loại học | Ví dụ |
|---|---|---|---|---|
| Classification | Nhãn / loại | Có | Supervised | Spam / Not spam |
| Regression | Số liên tục | Có | Supervised | Giá nhà, doanh thu |
| Clustering | Nhóm tự phát hiện | Không | Unsupervised | Chia nhóm khách hàng |

---

# 6. Ví dụ áp dụng trong doanh nghiệp

## Công ty thẩm mỹ

Classification:

```text
Khách có khả năng mua gói premium không? Yes/No
```

Regression:

```text
Dự đoán doanh thu tháng tới
```

Clustering:

```text
Chia khách hàng thành các nhóm: khách mới, khách trung thành, khách VIP
```

## Nhà máy nước

Classification:

```text
Sản phẩm lỗi hay không lỗi
```

Regression:

```text
Dự đoán nhu cầu sản xuất tuần tới
```

Clustering:

```text
Phân nhóm đại lý theo sản lượng mua và tần suất đặt hàng
```

---

# 7. Bài tập tự kiểm tra

Hãy xác định các bài toán sau là Classification, Regression hay Clustering.

1. Dự đoán giá căn hộ dựa trên diện tích và vị trí.
2. Phân loại email là spam hoặc không spam.
3. Chia khách hàng thành 4 nhóm dựa trên hành vi mua hàng.
4. Dự đoán doanh thu tháng sau.
5. Dự đoán bệnh nhân có bệnh hay không.
6. Phân nhóm sản phẩm theo đặc điểm giống nhau.
7. Dự đoán điểm thi của sinh viên.
8. Nhận diện ảnh là mèo, chó hoặc chim.

## Đáp án

| Câu | Dạng bài toán | Lý do |
|---:|---|---|
| 1 | Regression | Output là giá căn hộ, một con số |
| 2 | Classification | Output là spam/not spam |
| 3 | Clustering | Không có label, tự chia nhóm khách hàng |
| 4 | Regression | Output là doanh thu, một con số |
| 5 | Classification | Output là có bệnh/không bệnh |
| 6 | Clustering | Tự gom sản phẩm giống nhau |
| 7 | Regression | Output là điểm số |
| 8 | Classification | Output là nhãn mèo/chó/chim |

---

# 8. Kết luận cần nhớ

Machine Learning không phải là phép màu. Nó là quá trình học pattern từ dữ liệu.

Ba câu hỏi quan trọng khi gặp một bài toán ML:

```text
1. Dữ liệu của mình là gì?
2. Output mình muốn dự đoán là gì?
3. Output đó là nhãn, số, hay nhóm tự phát hiện?
```

Nếu output là nhãn → Classification.

Nếu output là số → Regression.

Nếu không có label và muốn chia nhóm → Clustering.

Pipeline chuẩn cần nhớ:

```text
Dữ liệu → xử lý → model → đánh giá
```

---

# 9. Bài tập luyện phân biệt các dạng bài toán ML

Hãy xác định các bài toán sau thuộc:

- Classification
- Regression
- Clustering

---

| # | Bài toán | Đáp án |
|---|---|---|
| 1 | Dự đoán khách hàng có hủy dịch vụ không | Classification |
| 2 | Dự đoán số tiền khách sẽ chi trong tháng tới | Regression |
| 3 | Chia người dùng app thành các nhóm hành vi giống nhau | Clustering |
| 4 | Dự đoán căn hộ thuộc phân khúc bình dân/trung cấp/cao cấp | Classification |
| 5 | Dự đoán thời gian giao hàng mất bao nhiêu phút | Regression |
| 6 | Phân nhóm sản phẩm theo lịch sử mua chung của khách | Clustering |
| 7 | Nhận diện giao dịch có gian lận hay không | Classification |
| 8 | Dự đoán lượng nước đóng chai cần sản xuất tuần sau | Regression |
| 9 | Chia đại lý thành các nhóm dựa trên doanh số và tần suất đặt hàng | Clustering |
| 10 | Dự đoán review của khách là tích cực/trung lập/tiêu cực | Classification |

---

## Mẹo nhớ nhanh

```text
Output là nhãn / loại
→ Classification

Output là số
→ Regression

Không có label, muốn tự chia nhóm
→ Clustering